name: Deploying Laravel App
on:
  push:
    branches:
      - hi

jobs:
  laravel-deploy:
    name: Deploying Laravel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy .env
        run: cp .env.example .env

      - name: Configure .env
        run: |
          sed -i "s/DB_HOST=127.0.0.1/DB_HOST=${{ secrets.DB_HOST }}/g" .env
          sed -i "s/DB_DATABASE=mydatabase/DB_DATABASE=${{ secrets.DB_DATABASE }}/g" .env
          sed -i "s/DB_USERNAME=mydatabaseuser/DB_USERNAME=${{ secrets.DB_USERNAME }}/g" .env
          sed -i "s/DB_PASSWORD=mypassword/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/g" .env

      - name: Artisan migrate
        run: php artisan migrate --force

      - name: Artisan optimize
        run: php artisan optimize

      - name: Clear cache
        run: php artisan cache:clear

      - name: Generate key
        run: php artisan key:generate

      - name: Deploy to cPanel
        uses: LittleEndianIO/cpanel-git-deploy@v3
        with:
#          host: ${{ secrets.CPANEL_HOST }}
#          username: ${{ secrets.CPANEL_USERNAME }}
#          password: ${{ secrets.CPANEL_PASSWORD }}
#          destination: /home/your-cpanel-username/

